<?php
return [
    'Контакты 1 город несколько точек' => [
        'group' => 'Контакты',
        'variant_name' => '1 город, несколько точек',
        'template' => 'Красный фон.webp',
        'section' => 'Веб',
        'fields' => ['city', 'city_summary'],
        'exportText' => true, // Экспорт .txt включён
        'city_summary_settings' => [
        ],
    ],
    'Контакты 1 точка' => [
        'group' => 'Контакты',
        'variant_name' => '1 точка',
        'template' => 'Красный фон с хинкали.webp',
        'section' => 'Веб',
        'fields' => ['city', 'city_summary'],
        'exportText' => true, // Экспорт .txt включён
        'max_locations' => 1, // Для JS (сколько блоков показать сразу)
        'max_locations_limit' => 1,
        'city_summary_soon_settings' => [
        ],
    ],
    'Контакты несколько точек и городов' => [
        'group' => 'Контакты',
        'variant_name' => 'Несколько городов, несколько точек',
        'template' => 'Красный фон с хинкали.webp',
        'section' => 'Веб',
        'fields' => ['main_header'], 
        'max_locations_limit' => 4,
        'city_list_header_settings' => [
            'startY' => 200,
            'fontSizeMainHeader' => 64,
            'fontSizeCity' => 53,
            'fontSizeAddr' => 36,
            'fontSizePhone' => 38
        ],
    ],
    
    'Обложка Весна живая несколько точек' => [
        'group' => 'Обложка Весна живая',
        'variant' => 'Список городов (до 4-х)',
        'template' => 'Обложка Весна.webp',
        'section' => 'Веб',
        'fields' => ['spring_list'], 
        'max_locations_limit' => 4,
        'spring_city_list_settings' => [
            'startY' => 369,
            'fontSizeCity' => 60,
            'fontSizeAddr' => 35,
            'color' => [255, 255, 255],
            'gapCityToAddr' => 23,
            'gapBetweenBlocks' => 149,
            'bulletRadius' => 10,
            'fontCity' => 'Brog-Semibold.otf',
            'fontAddr' => 'Polyplast-Regular.ttf'
        ],
    ],
    
    'Обложка Весна живая 1 точка' => [
        'group' => 'Обложка Весна живая',
        'variant' => 'Одна точка (центр)',
        'template' => 'Обложка Весна.webp',
        'section' => 'Веб',
        'fields' => ['city', 'address'],
        'text1' => [
            'template' => '{city}',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 65,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 830],
            'align' => 'center',
        ],
        'text2' => [
            'template' => '{address}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 45,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 971],
            'align' => 'center',
        ],
    ],
    
    'Обложка Весна живая ссылка' => [
        'group' => 'Обложка Весна живая',
        'variant' => 'С контактами и ссылкой',
        'template' => 'Обложка Весна с лого.webp',
        'section' => 'Веб',
        'fields' => ['link'],
        'text1' => [
            'template' => 'Лепим и варим',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 60,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 953],
            'align' => 'center',
        ],
        'text2' => [
            'template' => 'с любовью для вас',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 60,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 1039],
            'align' => 'center',
        ],
        'text3' => [
            'template' => 'хинкалыч.рф',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 47,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 1336],
            'align' => 'center',
        ],
        'text4' => [
            'template' => 'starikhinkalych',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 31,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [412, 1197],
            'align' => 'left',
        ],
        'text5' => [
            'template' => '{vk_id_clean}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 31,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [412, 1260],
            'width' => 420,
            'align' => 'left',
        ],
    ],
    
    'Обложка Весна живая 1 точка открытие' => [
        'group' => 'Обложка Весна живая',
        'variant' => 'Скоро открытие (с контактами)',
        'template' => 'Обложка Весна с лого Открытие.webp',
        'section' => 'Веб',
        'fields' => ['link', 'city', 'address'],
        'text1' => [
            'template' => 'Лепим и варим',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 60,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 750],
            'align' => 'center',
        ],
        'text2' => [
            'template' => 'с любовью для вас',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 60,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 836],
            'align' => 'center',
        ],
        'text3' => [
            'template' => 'хинкалыч.рф',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 47,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 1083],
            'align' => 'center',
        ],
        'text4' => [
            'template' => 'starikhinkalych',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 31,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [412, 942],
            'align' => 'left',
        ],
        'text5' => [
            'template' => '{vk_id_clean}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 31,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [412, 1007],
            'width' => 420,
            'align' => 'left',
        ],
        'text6' => [
            'template' => 'СКОРО ОТКРЫТИЕ!',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 40,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [0, 1233],
            'align' => 'center',
        ],
        'text7' => [
            'template' => '{city},',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 35,
            'width' => 1080,
            'color' => [0, 0, 0],
            'position' => [0, 1324],
            'align' => 'center',
        ],
        'text8' => [
            'template' => '{address}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 35,
            'width' => 704,
            'color' => [0, 0, 0],
            'position' => [190, 1381],
            'align' => 'center',
        ],
    ],
    
    'Обложка Весна живая горизонтальная ссылка справа снизу' => [
        'group' => 'Обложка Весна горизонт',
        'variant_name' => 'Ссылка справа снизу',
        'template' => 'Обложка Весна горизонт ссылка справа пониже.webp',
        'section' => 'Веб',
        'fields' => ['link', 'spring_h_list', 'noticebadge'],
        'spring_h_list_settings' => [
            'leftStartX'        => 365,
            'rightStartX'       => 1292,
            'maxWidth'          => 360,
            'maxWidthRight'     => 590,
            'cityWidthRight'    => 1900,
            'cityWidth'         => 590,
            'startY'            => 384,
            'centerYRight'      => 290,
            'fontSizeCity'      => 34,
            'fontSizeAddr'      => 25,
            'fontSizePhone'     => 23,
            'bulletMargin'      => 31,
            'bulletRadius'      => 7,
            'gapCityToAddr'     => 25,
            'gapBetweenBlocks'  => 42,
            'gapBetweenAddr'    => 30,
            'gapAddrToPhone'    => 17,
            'gapPhoneToNextAddr'=> 0,
            'lineSpacingInside' => 10,
            'color'             => [255, 255, 255],
            'maxCitiesRight'    => 1,
            'fontCity'          => 'Brog-Semibold.otf',
            'fontAddr'          => 'Polyplast-Regular.ttf',
            'fontPhone'         => 'Polyplast-Regular.ttf'
        ],
        'opening_badge_settings' => [
            'x' => 748,
            'y' => 558,
            'radius' => 10
        ],

        'text1' => [
            'template' => 'хинкалыч.рф',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 27,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1293, 519],
            'align' => 'left',
        ],
        'text2' => [
            'template' => 'starikhinkalych',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1342, 437],
            'align' => 'left',
        ],
        'text3' => [
            'template' => '{vk_id_clean}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1342, 476],
            'width' => 420,
            'align' => 'left',
        ],
    ],
    
    'Обложка Весна живая Горизонтальная ссылка справа' => [
        'group' => 'Обложка Весна горизонт',
        'variant_name' => 'Ссылка справа',
        'template' => 'Обложка Весна горизонт.webp',
        'section' => 'Веб',
        'fields' => ['link', 'spring_h_list', 'noticebadge'], 
        'spring_h_list_settings' => [
            'leftStartX'         => 330,
            'rightStartX'        => 1258,
            'maxWidth'           => 380,
            'cityWidth'          => 380,
            'startY'             => 384,
            'fontSizeCity'       => 34,
            'fontSizeAddr'       => 25,
            'fontSizePhone'      => 23,
            'bulletMargin'       => 31,
            'bulletRadius'       => 7,
            'gapCityToAddr'      => 25,
            'gapBetweenBlocks'   => 42,
            'gapBetweenAddr'     => 30,
            'gapAddrToPhone'     => 17,
            'gapPhoneToNextAddr' => 0,
            'lineSpacingInside'  => 10,
            'maxCitiesRight'     => 0,
            'color'              => [255, 255, 255],
            'fontCity'           => 'Brog-Semibold.otf',
            'fontAddr'           => 'Polyplast-Regular.ttf',
            'fontPhone'          => 'Polyplast-Regular.ttf'
        ],
        'text1' => [
            'template' => 'хинкалыч.рф',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 27,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1250, 424],
            'align' => 'left',
        ],
        'text2' => [
            'template' => 'starikhinkalych',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1290, 352],
            'align' => 'left',
        ],
        'text3' => [
            'template' => '{vk_id_clean}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1920,
            'color' => [255, 255, 255],
            'position' => [1290, 388],
            'width' => 420,
            'align' => 'left',
        ],
        'opening_badge_settings' => [
            'x' => 749,
            'y' => 558,
            'radius' => 10
        ],
    ],
    
        'Обложка Весна живая Горизонтальная Ссылка посередине' => [
            'group' => 'Обложка Весна горизонт',
            'variant_name' => 'Ссылка посередине',
            'template' => 'Обложка Весна горизонт Ссылка посередине.webp',
            'section' => 'Веб',
            'fields' => ['link', 'spring_h_list', 'noticebadge'], // Активирует новый блок полей
            'spring_h_list_settings' => [
                'leftStartX'        => 330,
                'rightStartX'       => 1258,
                'maxWidth'          => 380,
                'cityWidth'         => 380,
                'startY'            => 384,
                'fontSizeCity'      => 34,
                'fontSizeAddr'      => 25,
                'fontSizePhone'     => 23,
                'bulletMargin'      => 31,
                'bulletRadius'      => 7,
                'gapCityToAddr'     => 25,
                'gapBetweenBlocks'  => 42,
                'gapBetweenAddr'    => 30,
                'gapAddrToPhone'    => 10,
                'gapPhoneToNextAddr'=> 0,
                'lineSpacingInside' => 10,
                'color'             => [255, 255, 255],
                'fontCity'          => 'Brog-Semibold.otf',
                'fontAddr'          => 'Polyplast-Regular.ttf',
                'fontPhone'         => 'Polyplast-Regular.ttf'
            ],
        'opening_badge_settings' => [
            'x' => 748,
            'y' => 485,
            'radius' => 10
        ],
        'text1' => [
            'template' => 'хинкалыч.рф',
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 27,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [825, 427],
            'align' => 'left',
        ],
        'text2' => [
            'template' => 'starikhinkalych',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [873, 340],
            'align' => 'left',
        ],
        'text3' => [
            'template' => '{vk_id_clean}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 21,
            'width' => 1080,
            'color' => [255, 255, 255],
            'position' => [873, 377],
            'width' => 420,
            'align' => 'left',
        ],
    ],
    
    'Обложка Весна живая Горизонтальная чистое' => [
        'group' => 'Обложка Весна горизонт',
        'variant_name' => 'Чистое',
        'template' => 'Обложка Весна горизонт чистое.webp',
        'section' => 'Веб',
        'fields' => ['spring_h_list', 'noticebadge'],
        'spring_h_list_settings' => [
            'leftStartX'        => 330,
            'rightStartX'       => 1258,
            'maxWidth'          => 380,
            'cityWidth'         => 380,
            'startY'            => 384,
            'fontSizeCity'      => 34,
            'fontSizeAddr'      => 25,
            'fontSizePhone'     => 23,
            'bulletMargin'      => 31,
            'bulletRadius'      => 7,
            'gapCityToAddr'     => 25,
            'gapBetweenBlocks'  => 42,
            'gapBetweenAddr'    => 30,
            'gapAddrToPhone'    => 10,
            'gapPhoneToNextAddr'=> 0,
            'lineSpacingInside' => 10,
            'color'             => [255, 255, 255],
            'fontCity'          => 'Brog-Semibold.otf',
            'fontAddr'          => 'Polyplast-Regular.ttf',
            'fontPhone'         => 'Polyplast-Regular.ttf'
        ],
        'opening_badge_settings' => [
            'x' => 764,
            'y' => 558,
            'radius' => 10
        ],
    ],
    
    'Обложка Весна живая Горизонтальная много городов' => [
            'group' => 'Обложка Весна горизонт',
            'variant_name' => 'Много городов',
            'template' => 'Обложка Весна горизонт ссылка посередине.webp',
            'section' => 'Веб',
            'fields' => ['link', 'spring_h_list', 'noticebadge'],
            'spring_h_list_settings' => [
                'leftStartX'        => 330,
                'rightStartX'       => 1258,
                'maxWidth'          => 380,
                'cityWidth'         => 380,
                'startY'            => 384,
                'fontSizeCity'      => 25,
                'fontSizeAddr'      => 18,
                'fontSizePhone'     => 16,
                'bulletMargin'      => 31,
                'bulletRadius'      => 7,
                'gapCityToAddr'     => 25,
                'gapBetweenBlocks'  => 30,
                'gapBetweenAddr'    => 20,
                'gapAddrToPhone'    => 10,
                'gapPhoneToNextAddr'=> 0,
                'lineSpacingInside' => 10,
                'color'             => [255, 255, 255],
                'fontCity'          => 'Brog-Semibold.otf',
                'fontAddr'          => 'Polyplast-Regular.ttf',
                'fontPhone'         => 'Polyplast-Regular.ttf'
            ],
            'opening_badge_settings' => [
                'x' => 748,
                'y' => 558,
                'radius' => 10
            ],
            'text1' => [
                'template' => 'хинкалыч.рф',
                'font' => 'Brog-Semibold.otf',
                'fontSize' => 27,
                'width' => 1080,
                'color' => [255, 255, 255],
                'position' => [825, 520],
                'align' => 'left',
            ],
            'text2' => [
                'template' => 'starikhinkalych',
                'font' => 'Polyplast-Regular.ttf',
                'fontSize' => 21,
                'width' => 1080,
                'color' => [255, 255, 255],
                'position' => [874, 439],
                'align' => 'left',
            ],
            'text3' => [
                'template' => '{vk_id_clean}',
                'font' => 'Polyplast-Regular.ttf',
                'fontSize' => 21,
                'width' => 1080,
                'color' => [255, 255, 255],
                'position' => [874, 478],
                'width' => 420,
                'align' => 'left',
            ],
        ],
        
        'Режим Работы Главная' => [
        'group' => 'Режим Работы',
        'variant' => 'Главная (классический стиль)',
        'template' => 'Режим Работы Главная.webp',
        'section' => 'Веб',
        'handler' => 'drawMainSchedule', 
        'startY_single' => 860,
        'startY_double' => 820,
        'fields' => ['locCity1', 'address1', 'weekDays1', 'time1', 'weekDays5', 'time5'], 
        'fonts' => [
            'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 60],
            'time' => ['file' => 'Brog-Semibold.otf', 'size' => 95],
            'city_bottom' => ['file' => 'Polyplast-Regular.ttf', 'size' => 45],
            'address_bottom' => ['file' => 'Polyplast-Regular.ttf', 'size' => 45],
        ],
        'colors' => [
            'days' => [0, 0, 0],
            'time' => [148, 27, 27],
            'city_bottom' => [0, 0, 0],
            'address_bottom' => [0, 0, 0],
        ],
        'text1' => [
            'template' => "РЕЖИМ",
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 120,
            'width' => 1080,
            'lineHeight' => 1.6,
            'angle' => 0,
            'color' => [148, 27, 27],
            'position' => [0, 520],
            'maxHeight' => 400,
            'align' => 'center',
        ],
        'text2' => [
            'template' => "РАБОТЫ",
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 120,
            'width' => 1080,
            'lineHeight' => 1.6,
            'angle' => 0,
            'color' => [148, 27, 27],
            'position' => [0, 695],
            'maxHeight' => 400,
            'align' => 'center',
        ],
    ],
    
    'Режим Работы Динамичный' => [
        'group' => 'Режим Работы',
        'variant' => 'Динамичный (с логотипом)',
        'template' => 'Режим с лого 2.webp',
        'template_2' => 'Режим с лого 2.webp',
        'template_3' => 'Режим с лого 3.webp',
        'section' => 'Веб',
        'fields' => ['city', 'address1'],
        'max_locations' => 3,
        'exportText' => false,
        'text' => [
            'template' => '',
        ],
        'text1' => [
            'template' => "РЕЖИМ РАБОТЫ",
            'font' => 'Brog-Semibold.otf',
            'fontSize' => 63,
            'width' => 1080,
            'angle' => 0,
            'color' => [148, 27, 27],
            'position' => [0, 420],
            'align' => 'center',
        ],
        'text2' => [
            'template' => '{city}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 39,
            'width' => 1080,
            'angle' => 0,
            'color' => [0, 0, 0],
            'position' => [0, 530],
            'align' => 'center',
        ],
        'location_card_1' => [
            'startY' => 560, 
            'address_template' => '{address1}',
            'days1_template' => '{weekDays1}',
            'time1_template' => '{time1}',
            'days2_template' => '{weekDays5}',
            'time2_template' => '{time5}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
            ],
            'colors' => [
                'address' => [0, 0, 0],
                'days' => [0, 0, 0],
                'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0],
                'border' => [200, 200, 200, 0]
            ],
            'radius' => 30,
            'paddingY' => 37,
            'width' => 850,
            'xCenter' => 540,
            'marginBottom' => 30,
        ],
        'location_card_2' => [
            'startY' => 'auto',
            'address_template' => '{address2}',
            'days1_template' => '{weekDays2}',
            'time1_template' => '{time2}',
            'days2_template' => '{weekDays6}',
            'time2_template' => '{time6}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
            ],
            'colors' => [
                'address' => [0, 0, 0],
                'days' => [0, 0, 0],
                'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0],
                'border' => [200, 200, 200, 0]
            ],
            'radius' => 30,
            'paddingY' => 37,
            'width' => 850,
            'xCenter' => 540,
            'marginBottom' => 30,
        ],
        'location_card_3' => [
            'startY' => 'auto',
            'address_template' => '{address3}',
            'days1_template' => '{weekDays3}',
            'time1_template' => '{time3}',
            'days2_template' => '{weekDays7}',
            'time2_template' => '{time7}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 35],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
            ],
            'colors' => [
                'address' => [0, 0, 0],
                'days' => [0, 0, 0],
                'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0],
                'border' => [200, 200, 200, 0]
            ],
            'radius' => 30,
            'paddingY' => 37,
            'width' => 850,
            'xCenter' => 540,
            'marginBottom' => 30,
        ],
    ],
        
    'Режим Работы Без лого Динамичный' => [
        'group' => 'Режим Работы',
        'variant' => 'Динамичный (без логотипа)',
        'template' => 'Режим без лого.webp',
        'section' => 'Веб',
        'fields' => ['address1'],
        'max_locations' => 4,
        'exportText' => false,
        'location_card_1' => [
            'startY' => 915,
            'autoCenter' => true,
            'cityGap' => 25,
            'city_template' => '{locCity1}',
            'address_template' => '{address1}',
            'days1_template' => '{weekDays1}',
            'time1_template' => '{time1}',
            'days2_template' => '{weekDays5}',
            'time2_template' => '{time5}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
                'city' => ['file' => 'Polyplast-Regular.ttf', 'size' => 40]
            ],
            'colors' => [
                'address' => [0, 0, 0], 'days' => [0, 0, 0], 'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0], 'border' => [200, 200, 200, 0],
                'city' => [0, 0, 0],
            ],
            'radius' => 30, 'paddingY' => 37, 'width' => 850, 'xCenter' => 540, 'marginBottom' => 40,
        ],
        'location_card_2' => [
            'startY' => 'auto',
            'cityGap' => 25,
            'city_template' => '{locCity2}',
            'address_template' => '{address2}',
            'days1_template' => '{weekDays2}',
            'time1_template' => '{time2}',
            'days2_template' => '{weekDays6}',
            'time2_template' => '{time6}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
                'city' => ['file' => 'Polyplast-Regular.ttf', 'size' => 40]
            ],
            'colors' => [
                'address' => [0, 0, 0], 'days' => [0, 0, 0], 'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0], 'border' => [200, 200, 200, 0],
                'city' => [0, 0, 0],
            ],
            'radius' => 30, 'paddingY' => 37, 'width' => 850, 'xCenter' => 540, 'marginBottom' => 40,
        ],
        'location_card_3' => [
            'startY' => 'auto',
            'cityGap' => 25,
            'city_template' => '{locCity3}',
            'address_template' => '{address3}',
            'days1_template' => '{weekDays3}',
            'time1_template' => '{time3}',
            'days2_template' => '{weekDays7}',
            'time2_template' => '{time7}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
                'city' => ['file' => 'Polyplast-Regular.ttf', 'size' => 40]
            ],
            'colors' => [
                'address' => [0, 0, 0], 'days' => [0, 0, 0], 'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0], 'border' => [200, 200, 200, 0],
                'city' => [0, 0, 0],
            ],
            'radius' => 30, 'paddingY' => 37, 'width' => 850, 'xCenter' => 540, 'marginBottom' => 40,
        ],
        'location_card_4' => [
            'startY' => 'auto',
            'cityGap' => 25,
            'city_template' => '{locCity4}',
            'address_template' => '{address4}',
            'days1_template' => '{weekDays4}',
            'time1_template' => '{time4}',
            'days2_template' => '{weekDays8}',
            'time2_template' => '{time8}',
            'fonts' => [
                'address' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'days' => ['file' => 'Polyplast-Regular.ttf', 'size' => 33],
                'time' => ['file' => 'Brog-Semibold.otf', 'size' => 64],
                'city' => ['file' => 'Polyplast-Regular.ttf', 'size' => 40]
            ],
            'colors' => [
                'address' => [0, 0, 0], 'days' => [0, 0, 0], 'time' => [148, 27, 27],
                'background' => [255, 255, 255, 0], 'border' => [200, 200, 200, 0],
                'city' => [0, 0, 0],
            ],
            'radius' => 30, 'paddingY' => 37, 'width' => 850, 'xCenter' => 540, 'marginBottom' => 40,
        ],
    ],
    
     'Фон для созвонов' => [
        'template' => 'Фон для созвонов.webp',
        'section' => 'Веб',
        'fields' => ['name', 'topic'],
        'exportText' => false, 
        'text' => [
            'template' => '',
        ],
        'text1' => [
            'template' => '{name}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 30,
            'width' => 800,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [255, 255, 255], // Белый
            'position' => [100, 150],
            'maxHeight' => 200,
            'align' => 'left', // Выравнивание по левому краю
        ],
        'text2' => [
            'template' => 'Тема: {topic}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 30,
            'width' => 800,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [255, 255, 255], // Белый
            'position' => [1000, 150],
            'maxHeight' => 200,
            'align' => 'right',
        ],
    ],
    
    'Фон для созвонов (вертикальный)' => [
        'template' => 'Фон для созвонов вертикальный.webp',
        'section' => 'Веб',
        'fields' => ['name', 'topic'],
        'exportText' => false,
        'text' => [
            'template' => '',
        ],
        'text1' => [
            'template' => '{name}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 30,
            'width' => 800,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [255, 255, 255],
            'position' => [140, 310],
            'maxHeight' => 200,
            'align' => 'center',
        ],
        'text2' => [
            'template' => 'Тема: {topic}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 30,
            'width' => 800,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [255, 255, 255],
            'position' => [140, 370],
            'maxHeight' => 200,
            'align' => 'center',
        ],
    ],
    
        'Режим работы 1 адрес' => [
        'template' => 'Режим 1 адрес.webp',
        'section' => 'Веб',
        'fields' => ['other_time1', 'other_date1'],
        'exportText' => false, 
        'text' => [
            'template' => '',
        ],
        'text1' => [
            'template' => '{other_date1}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 70,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0],
            'position' => [0, 990],
            'maxHeight' => 200,
            'align' => 'center',
            
        ],
        'text2' => [
            'template' => '{other_time1}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 115,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0], 
            'position' => [0, 1180],
            'maxHeight' => 200,
            'align' => 'center',
            
            'shadow' => [
                'enabled' => true,
                'color' => [0, 0, 0],
                'alpha' => 125,
                'offset' => [0, 0],
                'blur_strength' => 8
            ],
        ],
    ],

    'Режим работы 2 адреса' => [
        'template' => 'Режим 2 адрес.webp',
        'section' => 'Веб',
        'fields' => ['other_time1', 'other_date1', 'other_date2', 'other_time2'],
        'exportText' => false,
        'text' => [
            'template' => '',
        ],
        'text1' => [
            'template' => '{other_date1}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 70,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0],
            'position' => [0, 590],
            'maxHeight' => 200,
            'align' => 'center',
            
        ],
        'text2' => [
            'template' => '{other_time1}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 115,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0], 
            'position' => [0, 780],
            'maxHeight' => 200,
            'align' => 'center',
            
            'shadow' => [
                'enabled' => true,
                'color' => [0, 0, 0],
                'alpha' => 125,
                'offset' => [0, 0],
                'blur_strength' => 8
            ],
        ],
        'text3' => [
            'template' => '{other_date2}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 70,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0],
            'position' => [0, 1160],
            'maxHeight' => 200,
            'align' => 'center',
            
        ],
        'text4' => [
            'template' => '{other_time2}',
            'font' => 'Polyplast-Regular.ttf',
            'fontSize' => 115,
            'width' => 1190,
            'lineHeight' => 1.2,
            'angle' => 0,
            'color' => [0, 0, 0], 
            'position' => [0, 1350],
            'maxHeight' => 200,
            'align' => 'center',
            
            'shadow' => [
                'enabled' => true,
                'color' => [0, 0, 0],
                'alpha' => 125,
                'offset' => [0, 0],
                'blur_strength' => 8
            ],
        ],
    ],

];